/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint8Struct = { data: BytesLike; securityZone: BigNumberish };

export type InEuint8StructOutput = [data: string, securityZone: bigint] & {
  data: string;
  securityZone: bigint;
};

export type InEuint32Struct = { data: BytesLike; securityZone: BigNumberish };

export type InEuint32StructOutput = [data: string, securityZone: bigint] & {
  data: string;
  securityZone: bigint;
};

export type PermissionStruct = { publicKey: BytesLike; signature: BytesLike };

export type PermissionStructOutput = [publicKey: string, signature: string] & {
  publicKey: string;
  signature: string;
};

export interface TrialVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "commitResults"
      | "commitments"
      | "createTrial"
      | "deployHospitalTrial"
      | "eip712Domain"
      | "encryptedAlertThreshold"
      | "encryptedTotalSeverity"
      | "getPoolCount"
      | "grantLicense"
      | "hospitalTrials"
      | "licenses"
      | "nextCommitId"
      | "nextHospitalTrialId"
      | "nextLicenseId"
      | "nextTokenId"
      | "nextTrialId"
      | "patientToTokenId"
      | "publishResults"
      | "publishedResults"
      | "registerData"
      | "requestLicense"
      | "runMatching"
      | "setAlertThreshold"
      | "submitAdverseEvent"
      | "submitEncryptedCohort"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DataRegistered"
      | "EIP712DomainChanged"
      | "EncryptedCohortSubmitted"
      | "HospitalTrialDeployed"
      | "LicenseGranted"
      | "LicenseRequested"
      | "ResultCommitted"
      | "ResultsPublished"
      | "SafetyAlert"
      | "TrialCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "commitResults",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTrial",
    values: [
      string,
      InEuint8Struct,
      InEuint32Struct,
      InEuint32Struct,
      InEuint32Struct,
      InEuint32Struct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deployHospitalTrial",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eip712Domain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedAlertThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedTotalSeverity",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolCount",
    values: [BigNumberish, PermissionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "grantLicense",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hospitalTrials",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "licenses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextCommitId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextHospitalTrialId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextLicenseId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextTrialId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "patientToTokenId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishResults",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "publishedResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerData",
    values: [
      string,
      InEuint8Struct,
      InEuint32Struct,
      InEuint32Struct,
      InEuint32Struct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLicense",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "runMatching",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAlertThreshold",
    values: [InEuint32Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAdverseEvent",
    values: [InEuint32Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedCohort",
    values: [BigNumberish, InEuint32Struct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "commitResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTrial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deployHospitalTrial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eip712Domain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedAlertThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedTotalSeverity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "grantLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hospitalTrials",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "licenses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextCommitId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextHospitalTrialId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextLicenseId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextTrialId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "patientToTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publishedResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestLicense",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "runMatching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAlertThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAdverseEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedCohort",
    data: BytesLike
  ): Result;
}

export namespace DataRegisteredEvent {
  export type InputTuple = [
    patient: AddressLike,
    tokenId: BigNumberish,
    ipfsCid: string
  ];
  export type OutputTuple = [patient: string, tokenId: bigint, ipfsCid: string];
  export interface OutputObject {
    patient: string;
    tokenId: bigint;
    ipfsCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EIP712DomainChangedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EncryptedCohortSubmittedEvent {
  export type InputTuple = [trialId: BigNumberish, count: BigNumberish];
  export type OutputTuple = [trialId: bigint, count: bigint];
  export interface OutputObject {
    trialId: bigint;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HospitalTrialDeployedEvent {
  export type InputTuple = [trialId: BigNumberish, analysisType: BigNumberish];
  export type OutputTuple = [trialId: bigint, analysisType: bigint];
  export interface OutputObject {
    trialId: bigint;
    analysisType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseGrantedEvent {
  export type InputTuple = [
    licenseId: BigNumberish,
    patient: AddressLike,
    pharma: AddressLike
  ];
  export type OutputTuple = [
    licenseId: bigint,
    patient: string,
    pharma: string
  ];
  export interface OutputObject {
    licenseId: bigint;
    patient: string;
    pharma: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LicenseRequestedEvent {
  export type InputTuple = [
    licenseId: BigNumberish,
    datasetId: BigNumberish,
    licensee: AddressLike
  ];
  export type OutputTuple = [
    licenseId: bigint,
    datasetId: bigint,
    licensee: string
  ];
  export interface OutputObject {
    licenseId: bigint;
    datasetId: bigint;
    licensee: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultCommittedEvent {
  export type InputTuple = [
    commitId: BigNumberish,
    datasetHash: BytesLike,
    merkleRoot: BytesLike
  ];
  export type OutputTuple = [
    commitId: bigint,
    datasetHash: string,
    merkleRoot: string
  ];
  export interface OutputObject {
    commitId: bigint;
    datasetHash: string;
    merkleRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResultsPublishedEvent {
  export type InputTuple = [
    trialId: BigNumberish,
    resultsHash: BytesLike,
    verified: boolean
  ];
  export type OutputTuple = [
    trialId: bigint,
    resultsHash: string,
    verified: boolean
  ];
  export interface OutputObject {
    trialId: bigint;
    resultsHash: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SafetyAlertEvent {
  export type InputTuple = [blockNumber: BigNumberish];
  export type OutputTuple = [blockNumber: bigint];
  export interface OutputObject {
    blockNumber: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrialCreatedEvent {
  export type InputTuple = [trialId: BigNumberish, sponsor: AddressLike];
  export type OutputTuple = [trialId: bigint, sponsor: string];
  export interface OutputObject {
    trialId: bigint;
    sponsor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrialVault extends BaseContract {
  connect(runner?: ContractRunner | null): TrialVault;
  waitForDeployment(): Promise<this>;

  interface: TrialVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  commitResults: TypedContractMethod<
    [datasetHash: BytesLike, merkleRoot: BytesLike],
    [bigint],
    "nonpayable"
  >;

  commitments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        sponsor: string;
        datasetHash: string;
        merkleRoot: string;
        committedAt: bigint;
      }
    ],
    "view"
  >;

  createTrial: TypedContractMethod<
    [
      name: string,
      inEncDiagnosisRequired: InEuint8Struct,
      inEncMinAge: InEuint32Struct,
      inEncMaxAge: InEuint32Struct,
      inEncLabMin: InEuint32Struct,
      inEncLabMax: InEuint32Struct
    ],
    [bigint],
    "nonpayable"
  >;

  deployHospitalTrial: TypedContractMethod<
    [analysisType: BigNumberish, dpEpsilon: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  eip712Domain: TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;

  encryptedAlertThreshold: TypedContractMethod<[], [bigint], "view">;

  encryptedTotalSeverity: TypedContractMethod<[], [bigint], "view">;

  getPoolCount: TypedContractMethod<
    [trialId: BigNumberish, permission: PermissionStruct],
    [bigint],
    "view"
  >;

  grantLicense: TypedContractMethod<
    [licenseId: BigNumberish],
    [void],
    "nonpayable"
  >;

  hospitalTrials: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        analysisType: bigint;
        dpEpsilon: bigint;
        totalPatients: bigint;
        encryptedSum: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  licenses: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, boolean] & {
        datasetId: bigint;
        licensee: string;
        priceWei: bigint;
        purpose: string;
        active: boolean;
      }
    ],
    "view"
  >;

  nextCommitId: TypedContractMethod<[], [bigint], "view">;

  nextHospitalTrialId: TypedContractMethod<[], [bigint], "view">;

  nextLicenseId: TypedContractMethod<[], [bigint], "view">;

  nextTokenId: TypedContractMethod<[], [bigint], "view">;

  nextTrialId: TypedContractMethod<[], [bigint], "view">;

  patientToTokenId: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  publishResults: TypedContractMethod<
    [commitId: BigNumberish, resultsHash: BytesLike],
    [void],
    "nonpayable"
  >;

  publishedResults: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  registerData: TypedContractMethod<
    [
      ipfsCid: string,
      inEncDiagnosisCode: InEuint8Struct,
      inEncAge: InEuint32Struct,
      inEncLabValue1: InEuint32Struct,
      inEncLabValue2: InEuint32Struct
    ],
    [bigint],
    "nonpayable"
  >;

  requestLicense: TypedContractMethod<
    [datasetId: BigNumberish, purpose: string],
    [bigint],
    "payable"
  >;

  runMatching: TypedContractMethod<
    [trialId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setAlertThreshold: TypedContractMethod<
    [threshold: InEuint32Struct],
    [void],
    "nonpayable"
  >;

  submitAdverseEvent: TypedContractMethod<
    [inEncSeverity: InEuint32Struct],
    [void],
    "nonpayable"
  >;

  submitEncryptedCohort: TypedContractMethod<
    [trialId: BigNumberish, inEncLabs: InEuint32Struct[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "commitResults"
  ): TypedContractMethod<
    [datasetHash: BytesLike, merkleRoot: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        sponsor: string;
        datasetHash: string;
        merkleRoot: string;
        committedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createTrial"
  ): TypedContractMethod<
    [
      name: string,
      inEncDiagnosisRequired: InEuint8Struct,
      inEncMinAge: InEuint32Struct,
      inEncMaxAge: InEuint32Struct,
      inEncLabMin: InEuint32Struct,
      inEncLabMax: InEuint32Struct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deployHospitalTrial"
  ): TypedContractMethod<
    [analysisType: BigNumberish, dpEpsilon: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eip712Domain"
  ): TypedContractMethod<
    [],
    [
      [string, string, string, bigint, string, string, bigint[]] & {
        fields: string;
        name: string;
        version: string;
        chainId: bigint;
        verifyingContract: string;
        salt: string;
        extensions: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "encryptedAlertThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "encryptedTotalSeverity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPoolCount"
  ): TypedContractMethod<
    [trialId: BigNumberish, permission: PermissionStruct],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantLicense"
  ): TypedContractMethod<[licenseId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hospitalTrials"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        analysisType: bigint;
        dpEpsilon: bigint;
        totalPatients: bigint;
        encryptedSum: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "licenses"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, boolean] & {
        datasetId: bigint;
        licensee: string;
        priceWei: bigint;
        purpose: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextCommitId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextHospitalTrialId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextLicenseId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextTrialId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "patientToTokenId"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "publishResults"
  ): TypedContractMethod<
    [commitId: BigNumberish, resultsHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "publishedResults"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registerData"
  ): TypedContractMethod<
    [
      ipfsCid: string,
      inEncDiagnosisCode: InEuint8Struct,
      inEncAge: InEuint32Struct,
      inEncLabValue1: InEuint32Struct,
      inEncLabValue2: InEuint32Struct
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestLicense"
  ): TypedContractMethod<
    [datasetId: BigNumberish, purpose: string],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "runMatching"
  ): TypedContractMethod<[trialId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAlertThreshold"
  ): TypedContractMethod<[threshold: InEuint32Struct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitAdverseEvent"
  ): TypedContractMethod<
    [inEncSeverity: InEuint32Struct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitEncryptedCohort"
  ): TypedContractMethod<
    [trialId: BigNumberish, inEncLabs: InEuint32Struct[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DataRegistered"
  ): TypedContractEvent<
    DataRegisteredEvent.InputTuple,
    DataRegisteredEvent.OutputTuple,
    DataRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "EIP712DomainChanged"
  ): TypedContractEvent<
    EIP712DomainChangedEvent.InputTuple,
    EIP712DomainChangedEvent.OutputTuple,
    EIP712DomainChangedEvent.OutputObject
  >;
  getEvent(
    key: "EncryptedCohortSubmitted"
  ): TypedContractEvent<
    EncryptedCohortSubmittedEvent.InputTuple,
    EncryptedCohortSubmittedEvent.OutputTuple,
    EncryptedCohortSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "HospitalTrialDeployed"
  ): TypedContractEvent<
    HospitalTrialDeployedEvent.InputTuple,
    HospitalTrialDeployedEvent.OutputTuple,
    HospitalTrialDeployedEvent.OutputObject
  >;
  getEvent(
    key: "LicenseGranted"
  ): TypedContractEvent<
    LicenseGrantedEvent.InputTuple,
    LicenseGrantedEvent.OutputTuple,
    LicenseGrantedEvent.OutputObject
  >;
  getEvent(
    key: "LicenseRequested"
  ): TypedContractEvent<
    LicenseRequestedEvent.InputTuple,
    LicenseRequestedEvent.OutputTuple,
    LicenseRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ResultCommitted"
  ): TypedContractEvent<
    ResultCommittedEvent.InputTuple,
    ResultCommittedEvent.OutputTuple,
    ResultCommittedEvent.OutputObject
  >;
  getEvent(
    key: "ResultsPublished"
  ): TypedContractEvent<
    ResultsPublishedEvent.InputTuple,
    ResultsPublishedEvent.OutputTuple,
    ResultsPublishedEvent.OutputObject
  >;
  getEvent(
    key: "SafetyAlert"
  ): TypedContractEvent<
    SafetyAlertEvent.InputTuple,
    SafetyAlertEvent.OutputTuple,
    SafetyAlertEvent.OutputObject
  >;
  getEvent(
    key: "TrialCreated"
  ): TypedContractEvent<
    TrialCreatedEvent.InputTuple,
    TrialCreatedEvent.OutputTuple,
    TrialCreatedEvent.OutputObject
  >;

  filters: {
    "DataRegistered(address,uint256,string)": TypedContractEvent<
      DataRegisteredEvent.InputTuple,
      DataRegisteredEvent.OutputTuple,
      DataRegisteredEvent.OutputObject
    >;
    DataRegistered: TypedContractEvent<
      DataRegisteredEvent.InputTuple,
      DataRegisteredEvent.OutputTuple,
      DataRegisteredEvent.OutputObject
    >;

    "EIP712DomainChanged()": TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;
    EIP712DomainChanged: TypedContractEvent<
      EIP712DomainChangedEvent.InputTuple,
      EIP712DomainChangedEvent.OutputTuple,
      EIP712DomainChangedEvent.OutputObject
    >;

    "EncryptedCohortSubmitted(uint256,uint256)": TypedContractEvent<
      EncryptedCohortSubmittedEvent.InputTuple,
      EncryptedCohortSubmittedEvent.OutputTuple,
      EncryptedCohortSubmittedEvent.OutputObject
    >;
    EncryptedCohortSubmitted: TypedContractEvent<
      EncryptedCohortSubmittedEvent.InputTuple,
      EncryptedCohortSubmittedEvent.OutputTuple,
      EncryptedCohortSubmittedEvent.OutputObject
    >;

    "HospitalTrialDeployed(uint256,uint8)": TypedContractEvent<
      HospitalTrialDeployedEvent.InputTuple,
      HospitalTrialDeployedEvent.OutputTuple,
      HospitalTrialDeployedEvent.OutputObject
    >;
    HospitalTrialDeployed: TypedContractEvent<
      HospitalTrialDeployedEvent.InputTuple,
      HospitalTrialDeployedEvent.OutputTuple,
      HospitalTrialDeployedEvent.OutputObject
    >;

    "LicenseGranted(uint256,address,address)": TypedContractEvent<
      LicenseGrantedEvent.InputTuple,
      LicenseGrantedEvent.OutputTuple,
      LicenseGrantedEvent.OutputObject
    >;
    LicenseGranted: TypedContractEvent<
      LicenseGrantedEvent.InputTuple,
      LicenseGrantedEvent.OutputTuple,
      LicenseGrantedEvent.OutputObject
    >;

    "LicenseRequested(uint256,uint256,address)": TypedContractEvent<
      LicenseRequestedEvent.InputTuple,
      LicenseRequestedEvent.OutputTuple,
      LicenseRequestedEvent.OutputObject
    >;
    LicenseRequested: TypedContractEvent<
      LicenseRequestedEvent.InputTuple,
      LicenseRequestedEvent.OutputTuple,
      LicenseRequestedEvent.OutputObject
    >;

    "ResultCommitted(uint256,bytes32,bytes32)": TypedContractEvent<
      ResultCommittedEvent.InputTuple,
      ResultCommittedEvent.OutputTuple,
      ResultCommittedEvent.OutputObject
    >;
    ResultCommitted: TypedContractEvent<
      ResultCommittedEvent.InputTuple,
      ResultCommittedEvent.OutputTuple,
      ResultCommittedEvent.OutputObject
    >;

    "ResultsPublished(uint256,bytes32,bool)": TypedContractEvent<
      ResultsPublishedEvent.InputTuple,
      ResultsPublishedEvent.OutputTuple,
      ResultsPublishedEvent.OutputObject
    >;
    ResultsPublished: TypedContractEvent<
      ResultsPublishedEvent.InputTuple,
      ResultsPublishedEvent.OutputTuple,
      ResultsPublishedEvent.OutputObject
    >;

    "SafetyAlert(uint256)": TypedContractEvent<
      SafetyAlertEvent.InputTuple,
      SafetyAlertEvent.OutputTuple,
      SafetyAlertEvent.OutputObject
    >;
    SafetyAlert: TypedContractEvent<
      SafetyAlertEvent.InputTuple,
      SafetyAlertEvent.OutputTuple,
      SafetyAlertEvent.OutputObject
    >;

    "TrialCreated(uint256,address)": TypedContractEvent<
      TrialCreatedEvent.InputTuple,
      TrialCreatedEvent.OutputTuple,
      TrialCreatedEvent.OutputObject
    >;
    TrialCreated: TypedContractEvent<
      TrialCreatedEvent.InputTuple,
      TrialCreatedEvent.OutputTuple,
      TrialCreatedEvent.OutputObject
    >;
  };
}
